version: '3.8'

services:
  dbmysql:
    image: mysql:latest
    restart: always
    container_name: db_auth
    environment:
      MYSQL_ROOT_PASSWORD: saravia
      MYSQL_DATABASE: auth_angular
      MYSQL_USER: luis.saravia
      MYSQL_PASSWORD: saravia
    ports:
      - "3321:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./table:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    networks:
      - app-network

  backend:
    depends_on:
      dbmysql:
        condition: service_healthy
    image: saraviadeveloper/api-auth
    restart: always
    
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    image: saraviadeveloper/frontend-auth
    restart: always

    ports:
      - "4400:4400"
    networks:
      - app-network

volumes:
  db_data: 

networks:
  app-network:
    name: "app-network"
    driver: bridge
    external: true
